# -*- coding: utf-8 -*-
"""Assignment_2 NNDL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2e8MXzIIwfyMsP_BNC1Fw9yewMLtiad
"""

# QUE 1

first_name = input("Enter first name \n")
last_name = input("Enter last name \n")

def string_alternative(name):
    return (name[::2])

def fullName(first_name, last_name):
    name = first_name + " " + last_name
    print ("full name : ", name)
    sa = string_alternative(name)
    print("alternate letters : ", sa)


fullName(first_name, last_name)

#Que 2

# function to return word_counts array after counting words in each line and storing them in word_counts array
def count_words(line, word_counts):
    words = line.split()
    # loop to count the occurance of each word
    for word in words:
        word_counts[word] = word_counts.get(word, 0) + 1
    return word_counts
# Main function
def main():
    input_filename = "input.txt"
    output_filename = "output.txt"

    try:
        # Reads the input file
        with open(input_filename, 'r') as input_file:
            readline = input_file.readlines()

        word_counts = {}
        for line in readline:
            line = line.strip()  # Remove leading/trailing whitespace
            # Function to count words
            word_count = count_words(line, word_counts)
        # Writing the input file lines to output file
        with open(output_filename, 'w') as output_file:
            for line in readline:
                output_file.write(line)

            output_file.write("\nWord_Count:\n")
            # Displaying the words and its count in output file
            for word, count in word_counts.items():
                output_file.write(f"{word}: {count}\n")
                print(f"{word}: {count}")

    except FileNotFoundError:
        print(f"File '{input_filename}' not found.")

if __name__ == "__main__":
    main()

# Function to convert height from inches to centimeters
def inches_to_cm(height_in_inches):
    return height_in_inches * 2.54

def main():

  # Enter customer count to take input
    cust_count = int(input("Enter the number of customers: "))
    inch_hyts = []

    # A.  Read heights in inches using nested loop
    for i in range(cust_count):
        hyt = float(input(f"Enter customer height {i+1} (in inches): "))
        inch_hyts.append(hyt)

    # Convert heights to centimeters using nested loop
    heights_cm = []
    for hyt in inch_hyts:

      # calling funtion for convertion
        cm_hyt = inches_to_cm(hyt)
        heights_cm.append(cm_hyt)

    # B.  Convert heights to centimeters using list comprehension
    heights_comp = [inches_to_cm(height) for height in inch_hyts]

  # print result
    print("customer heights  in centimeters (nested loop):", heights_cm)
    print("customer heights  in centimeters (list-comprehension):", heights_comp)

main()